name = "ParallelRandomFields"
uuid = "5519cec6-2252-4828-b89b-d1114f8bfbc2"
authors = ["Ludovic Räss <ludovic.rass@gmail.com> and contributors"]
version = "0.1.0"

[deps]
MAT = "23992714-dd62-5051-b70f-ba57cb901cac"
ParallelStencil = "94395366-693c-11ea-3b26-d9b7aac5d958"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
